obj-$(CONFIG_USE_DIRECT_IS_CONTROL) += fimc-is-interface-ischain.o \
		fimc-is-interface-library.o \
		fimc-is-interface-vra.o \
		fimc-is-interface-ddk.o

obj-$(CONFIG_USE_HOST_FD_LIBRARY) += fimc-is-interface-fd.o

EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2_dream/
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2_dream/include
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2_dream/hardware
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2_dream/hardware/api
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2_dream/vendor
