obj-$(CONFIG_CAMERA_FPGA_DPHY) += fimc-is-fpga-dphy.o

EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2_dream
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2_dream/include
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2_dream/vendor
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2_dream/sensor
